name: Condition Work Flow
on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job1"
  
  job2:
      runs-on: ubuntu-latest
      needs: job1

      if: ${{needs.job1.results == 'success'}}
      steps:
        - name: Step 1
          run: echo "This is job2"
    
    
