name: Condition Work Flow
on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chekout Repo
        uses: actions/checkout@v3

      - name: Reading File Data
        run: |
          FILE_CONTENT=$(cat temp.txt)
          echo "File Content: $FILE_CONTENT"
          echo "File Content: $FILE_CONTENT >> $GITHUB_ENV"  
      # here we set an value to env environment varaible using set-env
      # File Content this is an varaible name 
      # $FILE_CONTENT this is an value which we assign to varaible


      
  job2:
      runs-on: ubuntu-latest
      needs: job1
      env:
        FILE_CONTENT: ${{ env.FILE_CONTENT }}
      # if: ${{ env.FILE_CONTENT == 'dev' }}
      steps:
        - name: Step 1
          run: echo "This is job2 $FILE_CONTENT"
    
    
