name: Read File Content
on:
  push:
    branches: master
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.read_data.outputs.filedata }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Read File Content
      - id: read_data
        run: |
          FILE_CONTENT=$(cat temp.txt)
          echo "File_Content: $FILE_CONTENT"
          echo "::set-output name=filedata::$File_Content"
      
      
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.job1.outputs.output1}}
  #         OUTPUT2: ${{needs.job1.outputs.output2}}
  #       run: echo "$OUTPUT1 $OUTPUT2"
