name: Read File Content
on:
  push:
    branches: master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Read File Content
        id: read_file
        run: |
          FILE_CONTENT=$(cat temp.txt)
          echo "File Content: $FILE_CONTENT"
          echo "FILE_CONTENT=$FILE_CONTENT" >> $GITHUB_ENV
    outputs:
            file_content: ${{ steps.read_file.outputs.FILE_CONTENT }}
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - name: Use File Content
  #       run: |
  #         echo "Using file content in job 2: ${{ needs.job1.outputs.file_content
  #         }}"  










  
    
