name: Condition Work Flow
on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      FILE_CONTENT: " "
    steps:
      - name: Chekout Repo
        uses: actions/checkout@v3

      - name: Reading File Data
        run: |
          FILE_CONTENT=$(cat temp.txt)
          echo "File Content: $FILE_CONTENT"
          echo "::set-env name=FILE_CONTENT::"  
      # here we set an value to env environment varaible using set-env 


      
  job2:
      runs-on: ubuntu-latest
      needs: job1
      if: ${{ env.FILE_CONTENT == 'dev' }}
      steps:
        - name: Step 1
          run: echo "This is job2"
    
    
