name: Condition workflow
on:
  push:
    branches:
      - master
jobs:
  read-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Reading Data
        run: export FILE_DATA=$(cat temp.txt)

      - name: Display Data
        run: echo "Your File Data is :$FILE_DATA"
