name: Condition workflow
on:
  push:
    branches:
      - master
jobs:
  read-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Reading Data
        run: |
              FILE_CONTENT=$(cat temp.txt)
              echo "File Content: $FILE_CONTENT"

              
      - name: Condition
        run: |
            if [ "$FILE_CONTENT" = "Dev" ]; then
              echo "Yes This is dev"
              exit 0
            else
              echo "No, this is not dev"
              exit 1
            fi
