name: Condition workflow
on:
  push:
    branches:
      - master
jobs:
  read-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Reading Data
        run: |
              FILE_CONTENT=$(cat temp.txt)
        
      - name: Condition
        run: |
            if [ $FILE_CONTENT = "Dev" ]; then
                  echo "Yes This is dev"
            else
                  echo "No this is not dev"
                  exit 0
            fi
                
