name: Getting a data
on:
  push:
    branches:
      - master
jobs:
  getting-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Reading File From Repo
        run: cat temp.txt
